# Generated by Django 5.2.1 on 2025-05-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Beneficiário')),
                ('type_beneficiary', models.CharField(max_length=100, verbose_name='Tipo de Beneficiário')),
            ],
            options={
                'verbose_name': 'Beneficiário',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_benefit', models.CharField(max_length=100, verbose_name='Tipo de Benefício')),
                ('description_benefit', models.TextField(blank=True, null=True, verbose_name='Descrição do Benefício')),
            ],
            options={
                'verbose_name': 'Benefício',
                'ordering': ['type_benefit'],
            },
        ),
        migrations.CreateModel(
            name='Cost_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Centro de Custo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Centro de Custo')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'ordering': ['name'],
            },
        ),
    ]
