# Generated by Django 5.2.1 on 2025-05-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='type_benefit',
            field=models.CharField(choices=[('DN', 'Diárias Nacionais')], max_length=2, verbose_name='Tipo de Benefício'),
        ),
    ]
