# Generated by Django 5.2.1 on 2025-05-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_alter_benefit_type_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='type_benefit',
            field=models.CharField(max_length=100, verbose_name='Tipo de Benefício'),
        ),
    ]
