# Generated by Django 5.2.1 on 2025-05-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0003_alter_benefit_type_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='type_beneficiary',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Técnico', 'Técnico'), ('Diretor', 'Diretor'), ('Docente', 'Docente')], max_length=50, verbose_name='Tipo de Beneficiário'),
        ),
    ]
