# Generated by Django 5.2.1 on 2025-05-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0004_alter_beneficiary_type_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='type_beneficiary',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Técnico', 'Técnico'), ('Docente', 'Docente')], max_length=50, verbose_name='Tipo de Beneficiário'),
        ),
    ]
