# Generated by Django 5.2.1 on 2025-05-29 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0005_alter_beneficiary_type_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_concession', models.DateField(verbose_name='Data da Concessão')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Concessão')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Recursos')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.beneficiary', verbose_name='Beneficiário')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.benefit', verbose_name='Benefício')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.cost_center', verbose_name='Centro de Custo')),
            ],
            options={
                'verbose_name': 'Concessão',
                'ordering': ['date_concession'],
            },
        ),
    ]
