# Generated by Django 5.2.1 on 2025-06-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0006_concession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['type_benefit'], 'verbose_name': 'Tipos de Benefício', 'verbose_name_plural': 'Tipos de Benefícios'},
        ),
        migrations.AlterModelOptions(
            name='concession',
            options={'ordering': ['-date_concession'], 'permissions': [('can_generate_report', 'Pode gerar relatórios de concessões')], 'verbose_name': 'Concessão', 'verbose_name_plural': 'Concessões'},
        ),
        migrations.AlterModelOptions(
            name='cost_center',
            options={'ordering': ['name'], 'verbose_name': 'Centro de Custo', 'verbose_name_plural': 'Centros de Custos'},
        ),
        migrations.AlterField(
            model_name='benefit',
            name='description_benefit',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes sobre o benefício'),
        ),
        migrations.AlterField(
            model_name='concession',
            name='source',
            field=models.CharField(choices=[('UFU', 'Orçamento da UFU'), ('FAU', 'Receita de projetos (Via FAU)')], max_length=50, verbose_name='Fonte de Recursos'),
        ),
    ]
