# Generated by Django 5.2.1 on 2025-06-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0007_alter_benefit_options_alter_concession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Fonte de Recursos')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Fonte de Recursos')),
            ],
            options={
                'verbose_name': 'Fonte de Recursos',
                'verbose_name_plural': 'Fontes de Recursos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='concession',
            options={'ordering': ['-date_concession'], 'verbose_name': 'Concessão', 'verbose_name_plural': 'Concessões'},
        ),
        migrations.AlterField(
            model_name='concession',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.source', verbose_name='Fonte de Recursos'),
        ),
    ]
