# Generated by Django 5.2.1 on 2025-06-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0008_source_alter_concession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='type_source',
            field=models.CharField(default='Pública', max_length=50, verbose_name='Tipo de Fonte de Recursos'),
        ),
    ]
