# Generated by Django 5.2.1 on 2025-06-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0009_source_type_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='type_source',
        ),
    ]
